const allQuestionsAndAnswers = [
  {
    title: 'ইসলামিক কুইজ',
    quiz: true,
    subject: false,
    question: true,
    img: require('../assets/images/mosque.png'),
    islamicQuiz: [
      {
        id: 1,
        questionNo: '১',
        question: 'আমাদের সৃষ্টিকর্তার নাম কি?',
        hint1: 'খোদা',
        hint2: 'God',
        hint3: 'আল্লাহ',
        hint4: 'Lord',
        answer: 'আল্লাহ',
      },
      {
        id: 2,
        questionNo: '২',
        question: 'আল্লাহর কতগুলো নাম রয়েছে?',
        hint1: '৯৯',
        hint2: '১০০',
        hint3: 'একটি',
        hint4: 'অসংখ্য-অগণিত',
        answer: 'অসংখ্য-অগণিত',
      },
      {
        id: 3,
        questionNo: '৩',
        question: 'আমাদের সৃষ্টিকর্তা আল্লাহ্‌ কোথায় আছেন?',
        hint1: 'নির্দিষ্ট কিছু কিছু জায়গায়',
        hint2: 'সর্বত্র বিরাজমান',
        hint3: 'সপ্তাকাশের উপর আরশে আযীমে',
        hint4: 'মানুষের অন্তরে (ক্বলব)',
        answer: 'সপ্তাকাশের উপর আরশে আযীমে',
      },
      {
        id: 4,
        questionNo: '৪',
        question: 'তাওহীদ শব্দের অর্থ কি ?',
        hint1: 'একত্ববাদ',
        hint2: 'বিশ্বাস',
        hint3: 'অনুগত্য',
        hint4: 'একনিষ্ঠতা',
        answer: 'একত্ববাদ',
      },
      {
        id: 5,
        questionNo: '৫',
        question: 'তাওহীদ কত প্রকার?',
        hint1: '১',
        hint2: '২',
        hint3: '৩',
        hint4: '৪',
        answer: '৩',
      },
      {
        id: 6,
        questionNo: '৬',
        question: 'আল্লাহর ৯৯টি নাম মুখস্ত করার ফযীলত কি?',
        hint1: 'প্রতি হরফে ১০ নেকি ।',
        hint2: 'মুখস্ত এবং আমল করলে বিনিময়ে জান্নাত।',
        hint3: 'এর ফজিলত কুরআন-হাদিসে বর্ণিত নয় ।',
        hint4: 'নির্দিষ্ট কোন ফজিলত নাই ।',
        answer: 'মুখস্ত এবং আমল করলে বিনিময়ে জান্নাত।',
      },
      {
        id: 7,
        questionNo: '৭',
        question: '‘মুমিনের কলব আল্লাহর আরশ’ এটা কার কথা?',
        hint1: 'আল্লাহর',
        hint2: 'রাসূলের (স.)',
        hint3: 'মানুষের বানানো মিথ্যা কথা (জাল হাদীছ) ।',
        hint4: 'সাহাবীদের কথা ।',
        answer: 'মানুষের বানানো মিথ্যা কথা (জাল হাদীছ) ।',
      },
      {
        id: 8,
        questionNo: '৮',
        question: 'আল্লাহ কি নিরাকার?',
        hint1: 'হ্যাঁ কারণ তিনি সর্বত্র বিরাজমান ।',
        hint2: 'এ বিষয়ে কুরআনে কিছু বলা হয় নাই ।',
        hint3: 'না কারণ তাঁর অসিত্ব ও সত্তা আছে।',
        hint4: 'উপরের কোনটি সঠিক নয় ।',
        answer: 'না কারণ তাঁর অসিত্ব ও সত্তা আছে।',
      },
      {
        id: 9,
        questionNo: '৯',
        question: 'ঈমান শব্দের অর্থ কি ?',
        hint1: 'একত্ববাদ',
        hint2: 'অনুগত্য',
        hint3: 'একনিষ্ঠতা',
        hint4: 'বিশ্বাস',
        answer: 'বিশ্বাস',
      },
      {
        id: 10,
        questionNo: '১০',
        question: 'ঈমান কি কমে ও বাড়ে (পরিবর্তন হয় )?',
        hint1: 'না',
        hint2: 'হ্যাঁ',
        hint3: 'এ বিষয়ে কুরআন-হাদিসে কিছু বলা নাই ।',
        hint4: 'উপরের কোনটি সঠিক নয় ।',
        answer: 'হ্যাঁ',
      },
      {
        id: 11,
        questionNo: '১১',
        question: 'ঈমানের শাখা কতটি?',
        hint1: 'সত্তরের অধিক',
        hint2: 'একাত্তরের অধিক',
        hint3: 'বায়ান্নোর অধিক',
        hint4: 'শতাধিক',
        answer: 'সত্তরের অধিক',
      },
      {
        id: 12,
        questionNo: '১২',
        question: 'ঈমানের সর্বোচ্চ স্তর কি?',
        hint1: 'নামাজ/সালাত',
        hint2: 'রোজা/সিয়াম',
        hint3: 'কালিমা / লা-ইলাহা ইল্লাল্লাহু',
        hint4: 'হজ্জ',
        answer: 'কালিমা / লা-ইলাহা ইল্লাল্লাহু',
      },
      {
        id: 13,
        questionNo: '১৩',
        question: 'ঈমানের সর্বনিম্ন শাখা কি?',
        hint1: 'টাকা ধার/হাওলাদ/ঋণ দেওয়া',
        hint2: 'রাস্তা থেকে কষ্টদায়ক বস্তু অপসারণ করা',
        hint3: 'সত্য কথা বলা',
        hint4: 'গালি না দেওয়া',
        answer: 'রাস্তা থেকে কষ্টদায়ক বস্তু অপসারণ করা',
      },
      {
        id: 14,
        questionNo: '১৪',
        question: 'ঈমানের স্তম্ভ কয়টি?',
        hint1: '৫',
        hint2: '৬',
        hint3: '৭',
        hint4: '৮',
        answer: '৬',
      },
      {
        id: 15,
        questionNo: '১৫',
        question: 'আল্লাহর ফেরেশতাগণ কিসের তৈরী?',
        hint1: 'আগুনের',
        hint2: 'নূরের',
        hint3: 'মাটির',
        hint4: 'পানি ও বাতাসের',
        answer: 'নূরের',
      },
      {
        id: 16,
        questionNo: '১৬',
        question: 'ফেরেশতাদের সংখ্যা কত?',
        hint1: '২৬ হাজার',
        hint2: '৯২ হাজার',
        hint3: '১ লক্ষ ৩৫ হাজার',
        hint4: 'অসংখ্য ( আল্লাহ ছাড়া কেউ জানে না)',
        answer: 'অসংখ্য ( আল্লাহ ছাড়া কেউ জানে না)',
      },
      {
        id: 17,
        questionNo: '১৭',
        question: 'ওহী নাযিল করার দায়িত্ব কোন ফেরেশতার ছিল?',
        hint1: 'জিবরাঈল (আঃ)',
        hint2: 'ইসরাফীল (আঃ)',
        hint3: 'মালাকুল মওত (আঃ)',
        hint4: 'মীকাঈল (আঃ)',
        answer: 'জিবরাঈল (আঃ)',
      },
      {
        id: 18,
        questionNo: '১৮',
        question: 'কোন ফেরেশতাকে সকল ফেরেশতার সরদার বলা হয়?',
        hint1: 'জিবরাঈল (আঃ)',
        hint2: 'ইসরাফীল (আঃ)',
        hint3: 'মালাকুল মওত (আঃ)',
        hint4: 'মীকাঈল (আঃ)',
        answer: 'জিবরাঈল (আঃ)',
      },
      {
        id: 19,
        questionNo: '১৯',
        question: 'ইসরাফীল (আঃ) এর দায়িত্ব কি?',
        hint1: 'জান কবজ',
        hint2: 'বৃষ্টি বর্ষণ, উদ্ভিদ উৎপাদন',
        hint3: 'শিংগায় ফুৎকার',
        hint4: 'উপরের কোনটি নয়',
        answer: 'শিংগায় ফুৎকার',
      },
      {
        id: 20,
        questionNo: '২০',
        question: 'মীকাঈল (আঃ) এর দায়িত্ব কি?',
        hint1: 'জান কবজ',
        hint2: 'বৃষ্টি বর্ষণ, উদ্ভিদ উৎপাদন',
        hint3: 'শিংগায় ফুৎকার',
        hint4: 'উপরের কোনটি নয়',
        answer: 'বৃষ্টি বর্ষণ, উদ্ভিদ উৎপাদন',
      },
    ],
    total: '২০',
  },
  {
    title: 'ইসলামিক প্রশ্ন',
    quiz: false,
    subject: false,
    question: true,
    img: require('../assets/images/pray.png'),
    questionAndAnswer: [
      {
        id: 1,
        questionNo: '০১',
        question: 'পবিত্র কুরআনুল কারীমের সবচেয়ে ছোট সূরা কোনটি?',
        answer: 'সূরা কাউছার।',
      },
      {
        id: 2,
        questionNo: '০২',
        question: 'পবিত্র কুরআনুল কারীমের সবচেয়ে বড় আয়াত কোনটি?',
        answer: 'সূরা বাকারার ২৮২ নং আয়াত।',
      },
      {
        id: 3,
        questionNo: '০৩',
        question: 'সপ্তাহিক ঈদের দিন বলা হয় কোন দিনটি কে?',
        answer: 'জুমুআর দিন।',
      },
      {
        id: 4,
        questionNo: '০৪',
        question: 'মানবজাতির মধ্যে প্রথম হত্যাকান্ডের প্রচলন করেন কে?',
        answer: 'কাবিল।',
      },
      {
        id: 5,
        questionNo: '০৫',
        question: 'ইসলামের প্রথম মুআযযিন কে?',
        answer: 'বিলাল (রা:)।',
      },
      {
        id: 6,
        questionNo: '০৬',
        question:
          'দুনিয়ায় থাকতেই জান্নাতের সু-সংবাদ প্রাপ্ত সাহাবীর সংখ্যা কতো?',
        answer: '১০ জন।',
      },
      {
        id: 7,
        questionNo: '০৭',
        question: 'দাজ্জালের কোন চোখটি কানা হবে',
        answer: 'ডান চোখ।',
      },
      {
        id: 8,
        questionNo: '০৮',
        question: 'কুরআনের চূড়া বলা হয় কোন সূরা কে?',
        answer: 'সূরা বাকারা কে।',
      },
      {
        id: 9,
        questionNo: '০৯',
        question: 'জান্নাতী নারীদের সর্দার কে হবেন?',
        answer: 'ফাতিমা (রা:)।',
      },
      {
        id: 10,
        questionNo: '১০',
        question: 'জান্নাতে কাদের সংখ্যা বেশি হবে?',
        answer: 'দরিদ্রদের।',
      },
      {
        id: 11,
        questionNo: '১১',
        question: 'জাহান্নামে কাদের সংখ্যা বেশি হবে?',
        answer: 'নারীদের।',
      },
      {
        id: 12,
        questionNo: '১২',
        question: 'কোন দুই মুসলিম বাদশাহ পুরো পৃথিবী শাসন করেছেন?',
        answer: 'সুলায়মান (আ:) ও জুলকারনাইন',
      },
      {
        id: 13,
        questionNo: '১৩',
        question: 'OIC এর সদর দপ্তর কোথায়?',
        answer: 'জেদ্দায়।',
      },
      {
        id: 14,
        questionNo: '১৪',
        question: 'বর্তমান হিজরী সন কতো?',
        answer: '১৪৩৯।',
      },
      {
        id: 15,
        questionNo: '১৫',
        question: 'কোন সাহাবী (রা:) হিজরী সন গণনা প্রবর্তন করেন?',
        answer: 'উমার (রা:)।',
      },
      {
        id: 16,
        questionNo: '১৬',
        question: 'ঈমানের শাখা কতোটি?',
        answer: 'সত্তর এর অধিক।',
      },
      {
        id: 17,
        questionNo: '১৭',
        question: 'বিদআত কাকে বলে?',
        answer: 'ইবাদাতের নামে নতুন কিছু সৃষ্টি করলে',
      },
      {
        id: 18,
        questionNo: '১৮',
        question: 'জান্নাতে মানুষের বয়স কতো হবে?',
        answer: '৩৩।',
      },
      {
        id: 19,
        questionNo: '১৯',
        question: 'কোন সাহাবী (রা:) কে জীবন্ত শহীদ বলা হতো?',
        answer: 'তালহা বিন উবায়দুল্লাহ্।',
      },
      {
        id: 20,
        questionNo: '২০',
        question:
          'রাসূল (সা:) কোন বাহনে করে মসজিদুল হারাম থেকে মসজিদুল আকসায় পৌঁছেছিলেন?',
        answer: 'বোরাক।',
      },
      {
        id: 21,
        questionNo: '২১',
        question: "'উম্মুল কুরআন' বলা হয় কোন সূরা কে?",
        answer: 'সূরা ফাতিহা কে।',
      },
      {
        id: 22,
        questionNo: '২২',
        question: 'কুরআনুল কারীমের সবচেয় ফযিলতপূর্ণ আয়াত কোনটি?',
        answer: 'আয়াতুল কুরসী।',
      },
      {
        id: 23,
        questionNo: '২৩',
        question: 'কোন তিনটি সূরা শয়নকালে পড়া অধিক ফযিলতপূর্ণ?',
        answer: 'সূরা ইখলাছ, ফালাক ও নাস।',
      },
      {
        id: 24,
        questionNo: '২৪',
        question: 'মুসলিম ও অমুসলিমের মধ্যে পার্থক্যকারী ইবাদাত কোনটি?',
        answer: 'সালাত।',
      },
      {
        id: 25,
        questionNo: '২৫',
        question: 'কোন সাহাবী (রা:) কে উম্মতের আমানতদার উপাধি দেয়া হয়েছিলো?',
        answer: 'আবু উবাইদা বিন জাররাহ্ (রা:)।',
      },
      {
        id: 26,
        questionNo: '২৬',
        question:
          "কোন মহিলা সাহাবী (রা:) কে আল্লাহ তা'আলা জিবরীল (আ:) মারফত সালাম পাঠিয়েছেন?",
        answer: 'খাদিজা (রা:)।',
      },
      {
        id: 27,
        questionNo: '২৭',
        question: "'আর-রাহীকূল মাখতুম' গ্রন্থটি কোন বিষয়ে লিখা?",
        answer: 'রাসূল (সা:) এর জীবনী।',
      },
      {
        id: 28,
        questionNo: '২৮',
        question: 'আরবী কোন মাসে ঈদুল ফিতর উদযাপিত হয়?',
        answer: 'শাওয়াল মাসে।',
      },
      {
        id: 29,
        questionNo: '২৯',
        question: 'ইমাম মাহাদি কাদের নেতৃত্ব দিবেন?',
        answer: 'মুসলিমদের।',
      },
      {
        id: 30,
        questionNo: '৩০',
        question: 'দাজ্জাল কোন দুটি শহরে প্রবেশ করতে পারবে না',
        answer: 'মক্কা ও মদিনা।',
      },
      {
        id: 31,
        questionNo: '৩১',
        question: 'সর্বপ্রথম কে জান্নাতে প্রবেশ করবে?',
        answer: 'মুহাম্মদ (সা)।',
      },
      {
        id: 32,
        questionNo: '৩২',
        question: 'কুরআনের এক তৃতীয়াংশ বলা হয় কোন সূরা কে?',
        answer: 'সূরা ইখলাস।',
      },
      {
        id: 33,
        questionNo: '৩৩',
        question: 'শিরক কাকে বলে?',
        answer: 'আল্লাহর সাথে কোন কিছু শরীক করাকে শিরক বলে।',
      },
      {
        id: 34,
        questionNo: '৩৪',
        question: 'রাসূল (সা) সপ্তাহের কোন কোন দিন নফল সিয়াম পালন করতেন?',
        answer: 'সোমবার ও বৃহস্পতিবার।',
      },
      {
        id: 35,
        questionNo: '৩৫',
        question: 'অন্তরের মদ বলা হয় কোন জিনিসকে?',
        answer: 'গানকে।',
      },
      {
        id: 36,
        questionNo: '৩৬',
        question: 'পুরুষদের মধ্যে প্রথম কোন সাহাবী (রা) ইসলাম গ্রহণ করেছেন?',
        answer: 'আবু বকর (রা:)।',
      },
      {
        id: 37,
        questionNo: '৩৭',
        question: 'ফরয সালাতের পর সবচেয়ে গুরুত্বপূর্ণ সালাত কোনটি?',
        answer: 'রাতের (তাহাজ্জুদ) সালাত।',
      },
      {
        id: 38,
        questionNo: '৩৮',
        question: 'জান্নাত ও জাহান্নামের সংখ্যা কতো?',
        answer: '৮ ও ৭ টি।',
      },
      {
        id: 39,
        questionNo: '৩৯',
        question: 'গোলাম আহমাদ কাদিয়ানী কে ছিলেন?',
        answer: 'একজন মিথ্যা নবী দাবীদার।',
      },
      {
        id: 40,
        questionNo: '৪০',
        question: 'কিয়ামতের পূর্বে ক’জন মিথ্যা নবী দাবী করবে?',
        answer: '৩০ জন।',
      },
      {
        id: 41,
        questionNo: '৪১',
        question: 'তাফসীর ইবনে কাছীর গ্রন্থটির লেখক কে?',
        answer: 'ইসমাইল ইবনে কাছীর।',
      },
      {
        id: 42,
        questionNo: '৪২',
        question: 'বিচারদিবসে কয় শ্রেণীর মানুষ আল্লাহর আরশের নিচে স্থান পাবে?',
        answer: '৭ শ্রেণী।',
      },
      {
        id: 43,
        questionNo: '৪৩',
        question: 'কোন পাপকর্মটি আল্লাহ ও তার রাসূলের সাথে যুদ্ধ করার সমতুল্য?',
        answer: 'সুদ।',
      },
      {
        id: 44,
        questionNo: '৪৪',
        question: 'কোন পাপকর্মটির চেয়ে মাথায় পেরেক ঠুকে দেয়াটাও ভালো?',
        answer: 'কোন বেগানা নারীকে স্পর্শ করা।',
      },
      // {
      //   id: 45,
      //   questionNo: '৪৫',
      //   question: 'question',
      //   answer: 'answer',
      // },
      // {
      //   id: 46,
      //   questionNo: '৪৬',
      //   question: 'question',
      //   answer: 'answer',
      // },
      // {
      //   id: 47,
      //   questionNo: '৪৭',
      //   question: 'question',
      //   answer: 'answer',
      // },
      // {
      //   id: 48,
      //   questionNo: '৪৮',
      //   question: 'question',
      //   answer: 'answer',
      // },
      // {
      //   id: 49,
      //   questionNo: '৪৯',
      //   question: 'question',
      //   answer: 'answer',
      // },
      // {
      //   id: 50,
      //   questionNo: '৫০',
      //   question: 'question',
      //   answer: 'answer',
      // },
      // {
      //   id: 51,
      //   questionNo: '২১',
      //   question: 'question',
      //   answer: 'answer',
      // },
      // {
      //   id: 52,
      //   questionNo: '২২',
      //   question: 'question',
      //   answer: 'answer',
      // },
      // {
      //   id: 53,
      //   questionNo: '৫৩',
      //   question: 'question',
      //   answer: 'answer',
      // },
      // {
      //   id: 54,
      //   questionNo: '৫৪',
      //   question: 'question',
      //   answer: 'answer',
      // },
      // {
      //   id: 55,
      //   questionNo: '৫৫',
      //   question: 'question',
      //   answer: 'answer',
      // },
      // {
      //   id: 56,
      //   questionNo: '৫৬',
      //   question: 'question',
      //   answer: 'answer',
      // },
      // {
      //   id: 57,
      //   questionNo: '৫৭',
      //   question: 'question',
      //   answer: 'answer',
      // },
      // {
      //   id: 58,
      //   questionNo: '৫৮',
      //   question: 'question',
      //   answer: 'answer',
      // },
      // {
      //   id: 59,
      //   questionNo: '৫৯',
      //   question: 'question',
      //   answer: 'answer',
      // },
      // {
      //   id: 60,
      //   questionNo: '৬০',
      //   question: 'question',
      //   answer: 'answer',
      // },
    ],
    total: '৪৪',
  },
  {
    title: 'কম্পিউটার সম্পর্কে',
    quiz: false,
    subject: false,
    question: true,
    img: require('../assets/images/computer.png'),
    questionAndAnswer: [
      {
        id: 1,
        questionNo: '০১',
        question: 'কম্পিউটারের আবিষ্কারক কে?',
        answer: 'হাওয়ার্ড এ্যাইকিন।',
      },
      {
        id: 2,
        questionNo: '০২',
        question: 'কম্পিউটারের স্থায়ী স্মৃতিশক্তিকে কি বলে?',
        answer: 'Rom',
      },
      {
        id: 3,
        questionNo: '০৩',
        question: 'কম্পিউটারে কোনটি নেই?',
        answer: 'বুদ্ধি বিবেচনা।',
      },
      {
        id: 4,
        questionNo: '০৪',
        question: 'কোনটি কম্পিউটারের সকল কার্যক্রম নিয়ন্ত্রণ করে?',
        answer: 'সেন্ট্রাল প্রসেসিং ইউনিট।',
      },
      {
        id: 5,
        questionNo: '০৫',
        question: 'কম্পিউটার শব্দের অর্থ কি?',
        answer: 'গননাকারী যন্ত্র।',
      },
      {
        id: 6,
        questionNo: '০৬',
        question: 'ই-মেইল কি?',
        answer: 'ইলেকট্রনিক মেইল।',
      },
      {
        id: 7,
        questionNo: '০৭',
        question: 'কম্পিউটারের ব্রেইন বলা হয় কাকে?',
        answer: 'মাইক্রো প্রসেসর।',
      },
      {
        id: 8,
        questionNo: '০৮',
        question: 'কম্পিউটারের যন্ত্রাংশ বা যন্ত্রকে কি বলে?',
        answer: 'হার্ডওয়্যার।',
      },
      {
        id: 9,
        questionNo: '০৯',
        question: 'বর্তমান কম্পিউটার জগতের কিংবদন্তি কে?',
        answer: 'বিল গেটস।',
      },
      {
        id: 10,
        questionNo: '১০',
        question: 'কম্পিউটার বায়োস (BIOS) কি?',
        answer: 'Basic Input-Output System',
      },
      {
        id: 11,
        questionNo: '১১',
        question: 'কম্পিউটারের প্রধান প্রিন্টেড সার্কিট বোর্ডকে কি বলা হয়?',
        answer: 'মাদারবোর্ড।',
      },
      {
        id: 12,
        questionNo: '১২',
        question: 'কম্পিউটার র‍্যাম কি?',
        answer: 'স্মৃতিশক্তি।',
      },
      {
        id: 13,
        questionNo: '১৩',
        question: 'কম্পিউটারের এই ‘#’ চিহ্ন কে কি বলে?',
        answer: 'হ্যাস চিহ্ন।',
      },
      {
        id: 14,
        questionNo: '১৪',
        question: 'Net অর্থ কি?',
        answer: 'জাল।',
      },
      {
        id: 15,
        questionNo: '১৫',
        question: 'মাইক্রো শব্দের অর্থ কি?',
        answer: 'ক্ষুদ্রাকার।',
      },
      {
        id: 16,
        questionNo: '১৬',
        question:
          'অসংখ্য কম্পিউটারের সমন্বয়য়ে গঠিত বিশ্বব্যাপী কম্পিউটার নেটওয়ার্ককে কি বলা হয়?',
        answer: 'ইন্টারনেট।',
      },
      {
        id: 17,
        questionNo: '১৭',
        question: 'কম্পিউটারের ব্যবহার নয় কোনটি?',
        answer: 'স্বপ্ন দেখা।',
      },
      {
        id: 18,
        questionNo: '১৮',
        question: 'মাউস ক্লিক বলতে কি বুঝায়?',
        answer: 'মাউসের বাম বোতামে চাপা।',
      },
      {
        id: 19,
        questionNo: '১৯',
        question: 'কম্পিউটার শব্দের উৎপত্তি কোন শব্দ থেকে?',
        answer: 'Compute শব্দ থেকে।',
      },
      {
        id: 20,
        questionNo: '২০',
        question: 'কম্পিউটারে কয় ধরনের ড্রাইভ থাকে?',
        answer: '৩ ধরনের।',
      },
      {
        id: 21,
        questionNo: '২১',
        question: 'পাওয়ার-পয়েন্ট ফাইলকে কি বলা হয়?',
        answer: 'প্রেজেনটেশন।',
      },
      {
        id: 22,
        questionNo: '২২',
        question: 'কোনটি ডাটা সংরক্ষণ ও স্থানান্তরের ব্যবহৃত হয়?',
        answer: 'পেনড্রাইভ।',
      },
      {
        id: 23,
        questionNo: '২৩',
        question: 'কম্পিউটারে বাংলা লেখার সফটওয়্যারের নাম কি?',
        answer: 'বিজয়।',
      },
      {
        id: 24,
        questionNo: '২৪',
        question: 'তথ্য প্রযুক্তির শাখা নয় কোনটি?',
        answer: 'ডাক বিভাগ।',
      },
      {
        id: 25,
        questionNo: '২৫',
        question: 'অপারেটিং সিষ্টেম হচ্ছে-',
        answer: 'মানুষের মস্তিস্কের বুদ্ধি।',
      },
      {
        id: 26,
        questionNo: '২৬',
        question: 'Find কমান্ড থাকে কোন মেনুতে?',
        answer: 'Edit',
      },
      {
        id: 27,
        questionNo: '২৭',
        question: 'অক্ষরের আকার আকৃতি পরিবর্তন করতে হয়-',
        answer: 'ফন্ট ডায়লগ বক্সে।',
      },
      {
        id: 28,
        questionNo: '২৮',
        question: 'মানুষের দেহকে যদি হার্ডওয়্যার ধরা হয় তাহলে সফ্টওয়্যার-',
        answer: 'প্রাণ।',
      },
      {
        id: 29,
        questionNo: '২৯',
        question: 'কম্পিউটারের বুদ্ধি মা্নুষের চেয়ে-',
        answer: 'কম।',
      },
      {
        id: 30,
        questionNo: '৩০',
        question: 'কম্পিউটারে ব্যবহৃত প্রোগ্রাম সমষ্টিকে কি বলে?',
        answer: 'সফটওয়্যার।',
      },
      {
        id: 31,
        questionNo: '৩১',
        question: 'কম্পিউটারের কাজের গতি কি দ্বারা প্রকাশ করা হয়?',
        answer: 'ন্যানো সেকেন্ড',
      },
      {
        id: 32,
        questionNo: '৩২',
        question: 'কোনটি ছাড়া হার্ডওয়্যার কাজ করে না?',
        answer: 'সফ্টওয়্যার।',
      },
      {
        id: 33,
        questionNo: '৩৩',
        question: 'কোন কাজ করার জন্য কম্পিউটারকে কি প্রদান করতে হয়?',
        answer: 'তথ্য বা ডাটা।',
      },
      {
        id: 34,
        questionNo: '৩৪',
        question: 'কম্পিউটার কিভাবে তথ্য প্রক্রিয়ার কাজ করে?',
        answer: 'নির্দেশ অনুযায়ী।',
      },
      {
        id: 35,
        questionNo: '৩৫',
        question: 'কম্পিউটার যন্ত্র কোন ভাষা বোঝে?',
        answer: 'নিজস্ব ভাষা।',
      },
      {
        id: 36,
        questionNo: '৩৬',
        question: 'কম্পিউটারের আউটপুট যন্ত্র নয় কোনটি?',
        answer: 'স্ক্যানার।',
      },
      {
        id: 37,
        questionNo: '৩৭',
        question: 'সবচেয়ে শক্তিশালী কম্পিউটার হলো',
        answer: 'সুপার কম্পিউটার।',
      },
      {
        id: 38,
        questionNo: '৩৮',
        question: 'কম্পিউটার কার নির্দেশ অনুযায়ী কাজ করে?',
        answer: 'মানুষের।',
      },
      {
        id: 39,
        questionNo: '৩৯',
        question: 'শুরুতে কম্পিউটার দিয়ে কোন কাজটি করানো হত?',
        answer: 'গণনার।',
      },
      {
        id: 40,
        questionNo: '৪০',
        question: 'কার্সর (Cursor) কি?',
        answer: 'আলোক রেখা।',
      },
      {
        id: 41,
        questionNo: '৪১',
        question: 'উইন্ডোজ আসলে কিসের মতো?',
        answer: 'খোলা জানালা।',
      },
      {
        id: 42,
        questionNo: '৪২',
        question: 'অক্ষর কাটা বা মোছার জন্য কোন কমান্ড ব্যবহার করা হয়?',
        answer: 'ডিলিট বা ব্যাকস্পেস।',
      },
      {
        id: 43,
        questionNo: '৪৩',
        question: 'কোন বিজ্ঞানী কম্পিউটার ভাইরাস নামকরণ করেন?',
        answer: 'ফ্রেড কোহেন।',
      },
      {
        id: 44,
        questionNo: '৪৪',
        question: 'ডেটা ফাইলসমুহ আক্রমণ করে কোন ভাইরাস?',
        answer: 'ম্যাক্রো ভাইরাস।',
      },
      {
        id: 45,
        questionNo: '৪৫',
        question: 'মাউসকে ঝুলিয়ে ধরনের কিসের মতো দেখায়?',
        answer: 'ইদুরের মত।',
      },
      {
        id: 46,
        questionNo: '৪৬',
        question: 'ফাইল সেভ করার জন্য কোন মেনুর প্রয়োজন?',
        answer: 'ফাইল মেনু।',
      },
      {
        id: 47,
        questionNo: '৪৭',
        question: 'কম্পিউটার ভুল ফলাফল প্রদর্শন করলে বুঝতে হবে-',
        answer: 'ডাটা ইনপুট করায় ভুল হয়েছে।',
      },
      {
        id: 48,
        questionNo: '৪৮',
        question: 'ইনপুট ডিভাইস কোনটি?',
        answer: 'কিবোর্ড।',
      },
      {
        id: 49,
        questionNo: '৪৯',
        question: '0-09 পর্যন্ত Key গুলোর নাম কি?',
        answer: 'Numeric key.',
      },
      {
        id: 50,
        questionNo: '৫০',
        question: 'কোনটি স্পেশাল Key?',
        answer: 'Space bar',
      },
      {
        id: 51,
        questionNo: '৫১',
        question: 'MS word-এ Select All এর শর্টকাট কমান্ড কি?',
        answer: 'Ctrl+A',
      },
      {
        id: 52,
        questionNo: '৫২',
        question: 'LAN এর পূর্ণ নাম লিখ?',
        answer: 'Local Area Network',
      },
      {
        id: 53,
        questionNo: '৫৩',
        question: 'WWW এর পূর্ণ নাম লিখ?',
        answer: 'World Wide Web',
      },
      {
        id: 54,
        questionNo: '৫৪',
        question: 'মেনুবারে কয়টি মেনু আছে।',
        answer: '৯টি।',
      },
      {
        id: 55,
        questionNo: '৫৫',
        question: 'Save কোন মেনুতে রয়েছে?',
        answer: 'File মেনুতে ।',
      },
      {
        id: 56,
        questionNo: '৫৬',
        question: 'Save এর সর্টকাট কমান্ড লিখ।',
        answer: 'Ctrl+S',
      },
      {
        id: 57,
        questionNo: '৫৭',
        question: 'File অর্থ কি?',
        answer: 'নথিপত্র।',
      },
      {
        id: 58,
        questionNo: '৫৮',
        question: 'Data Processing কয় প্রকার?',
        answer: '৩ প্রকার।',
      },
      {
        id: 59,
        questionNo: '৫৯',
        question: 'জ্জ্ব কিভাবে লিখতে হয়?',
        answer: 'জ্ জ্ ব',
      },
      {
        id: 60,
        questionNo: '৬০',
        question: 'মাইক্রোসফ্ট উইন্ডোজ 3.1 বাজারে আসে-',
        answer: '১৯৯২ সালে।',
      },
    ],
    total: '৬০',
  },
  {
    title: 'বাংলাদেশ বিষয়াবলী',
    quiz: false,
    subject: true,
    question: true,
    img: require('../assets/images/bangladesh.png'),
    allSubjects: [
      {
        quiz: false,
        subject: false,
        question: true,
        subjectNo: '০১',
        title: 'সাধারণ জ্ঞান বাংলাদেশ বিষয়াবলী',
        questionAndAnswer: [
          {
            id: 1,
            questionNo: '০১',
            question: 'যশোর জেলায় অবস্থিত বিল?',
            answer: 'ভবদহ',
          },
          {
            id: 2,
            questionNo: '০২',
            question: 'জাতীয় পতাকা দিবস?',
            answer: '২ মার্চ',
          },
          {
            id: 3,
            questionNo: '০৩',
            question: 'বাংলাদেশে ২য় সংখ্যাগরিষ্ঠ উপজাতি?',
            answer: 'সাঁওতাল',
          },
          {
            id: 4,
            questionNo: '০৪',
            question: 'বাংলাদেশে উপজাতীয় ভাষার সংখ্যা?',
            answer: '৩২টি',
          },
          {
            id: 5,
            questionNo: '০৫',
            question: 'বাংলাদেশে গারো উপজাতি বাস করে?',
            answer: 'ময়মনসিংহ, টাঙ্গাইল ও নেত্রকোনায়',
          },
          {
            id: 6,
            questionNo: '০৬',
            question: 'বাংলাদেশে চাকমা উপজাতি বাস করে প্রধানত?',
            answer: 'রাঙ্গামাটি ও খাগড়াছড়িতে',
          },
          {
            id: 7,
            questionNo: '০৭',
            question: 'বাংলাদেশে সবচেয়ে বেশি লোক বাস করে?',
            answer: 'বৃহত্তর ঢাকা জেলায়',
          },
          {
            id: 8,
            questionNo: '০৮',
            question: 'ঢাকার পূর্ব নাম?',
            answer: 'জাহাঙ্গীর নগর',
          },
          {
            id: 9,
            questionNo: '০৯',
            question: 'বাংলাদেশ ক্রিকেট ওয়ানডে স্ট্যাটাস লাভ করে?',
            answer: '১৯৯৭সালে',
          },
          {
            id: 10,
            questionNo: '১০',
            question: 'বাংলাদেশের বৃহত্তম বিল কোনটি?',
            answer: 'চলন বিল।',
          },
          {
            id: 11,
            questionNo: '১১',
            question: 'বাংলাদেশের সর্বাধিক চা বাগান কোন জেলায় অবস্থিত?',
            answer: 'মৌলভীবাজার।',
          },
          {
            id: 12,
            questionNo: '১২',
            question: 'বাংলাদেশের পুলিশ মুক্তিযুদ্ধ জাদুঘর কোথায় অবস্থিত?',
            answer: 'রাজারবাগ, ঢাকা।',
          },
          {
            id: 13,
            questionNo: '১৩',
            question:
              'বাংলাদেশের কোন জেলাটির নামকরণ করা হয়েছে একটি নদীর নাম অনুসারে?',
            answer: 'ফেনী।',
          },
          {
            id: 14,
            questionNo: '১৪',
            question: 'বাঙালি ও যমুনা নদীর সংযোগ কোথায় হয়েছে?',
            answer: 'বগুড়ায়।',
          },
          {
            id: 15,
            questionNo: '১৫',
            question: 'আয়তনের দিক থেকে বিশ্বে বাংলাদেশের অবস্থান কত তম?',
            answer: '৯০ তম।',
          },
          {
            id: 16,
            questionNo: '১৬',
            question: 'বাংলাদেশের প্রথম নিরক্ষরতামুক্ত গ্রাম কোনটি?',
            answer: 'কচুবাড়ির কৃষ্টপুর, ঠাকুরগাঁও।',
          },
          {
            id: 17,
            questionNo: '১৭',
            question: '‘রূপসী বাংলাদেশ’ কোন এলাকাকে ঘোষণা দেয়া হয়েছে?',
            answer: 'সোনারগাঁয়ের জাদুঘর এলাকাকে।',
          },
          {
            id: 18,
            questionNo: '১৮',
            question: 'বাংলাদেশের প্রথম জাতীয় পতাকার নকশা কে তৈরি করেন?',
            answer: 'শিব নারায়ণ দাস।',
          },
          {
            id: 19,
            questionNo: '১৯',
            question: 'বাংলাদেশের প্রথম মুদ্রা চালু হয় কত সালে?',
            answer: '৪ মার্চ, ১৯৭২ সালে।',
          },
          {
            id: 20,
            questionNo: '২০',
            question: '‘জীবন তরী’ কী?',
            answer: 'একটি ভাসমান হাসপাতাল।',
          },
          {
            id: 21,
            questionNo: '২১',
            question: 'বাংলাদেশ বিমানের প্রতীক কী?',
            answer: 'উড়ন্ত বলাকা।',
          },
          {
            id: 22,
            questionNo: '২২',
            question: '‘নজরুল মঞ্চ’ কোথায় অবস্থিত?',
            answer: 'বাংলা একাডেমী প্রাঙ্গণে।',
          },
          {
            id: 23,
            questionNo: '২৩',
            question: 'বাংলাদেশের আবহাওয়া অধিদপ্তর কোন মন্ত্রণালয়ের অধীন?',
            answer: 'প্রতিরক্ষা মন্ত্রণালয়ের অধীন।',
          },
          {
            id: 24,
            questionNo: '২৪',
            question: 'মুসলিম সাহিত্য সমাজের প্রতিষ্ঠাতা কে?',
            answer: 'নওয়াব আবদুল লতিফ।',
          },
          {
            id: 25,
            questionNo: '২৫',
            question: 'বাংলাদেশের মোট সীমান্ত দৈর্ঘ্য কত কি.মি.?',
            answer: '৪৭১৯ কি.মি.',
          },
          {
            id: 26,
            questionNo: '২৬',
            question: 'বাংলাদেশের বৃহত্তর জেলা কতটি ?',
            answer: '১৯টি',
          },
          {
            id: 27,
            questionNo: '২৭',
            question: 'বাংলাদেশের কুয়েত সিটি বলা হয় কোন অঞ্চল কে?',
            answer: 'খুলনা',
          },
          {
            id: 28,
            questionNo: '২৮',
            question: 'বাংলাদেশের প্রথম নারী তথ্য কর্মকর্তা কে?',
            answer: 'কামরুন নাহার',
          },
          {
            id: 29,
            questionNo: '২৯',
            question: 'মিয়ানমার বাংলাদেশের কোনদিকে অাবস্থিত?',
            answer: 'দক্ষিণপূর্ব',
          },
          {
            id: 30,
            questionNo: '৩০',
            question: 'বাংলাদেশ-মিয়ানমার মৈত্রী সেতু কোথায় অবস্থিত?',
            answer: 'কক্সবাজার',
          },
          {
            id: 31,
            questionNo: '৩১',
            question: 'ভারতের সাথে বাংলাদেশের সীমান্ত দৈর্ঘ্য কত কিলোমিটার ?',
            answer: '৩৭১৫ কিলোমিটার',
          },
          {
            id: 32,
            questionNo: '৩২',
            question: 'বাংলাদেশের সীমান্তবর্তী ভারতের রাজ্য কয়টি?',
            answer: '৫টি',
          },
          {
            id: 33,
            questionNo: '৩৩',
            question: 'বাংলাদেশের ক্ষেত্রফল কত বর্গমাইল ?',
            answer: '৫৬,৫০১ বর্গমাইল',
          },
          {
            id: 34,
            questionNo: '৩৪',
            question: 'বাংলাদেশর মোট সীমারেখার পরিমাপ কত?',
            answer: '৫১৩৮ কি.মি.',
          },
          {
            id: 35,
            questionNo: '৩৫',
            question: 'বাংলাদেশের মোট সীমান্ত দৈর্ঘ্য কত কি.মি. ?',
            answer: '৪৭১৯ কি.মি',
          },
          {
            id: 36,
            questionNo: '৩৬',
            question: 'শেওলা স্থলবন্দর কোথায় অবস্থিত?',
            answer: 'সিলেট',
          },
          {
            id: 37,
            questionNo: '৩৭',
            question:
              'বাংলাদেশের সীমান্তবর্তী কোন জেলার সাথে ভারতের কোন সংযোগ নেই?',
            answer: 'বান্দরবান',
          },
          {
            id: 38,
            questionNo: '৩৮',
            question: 'বাংলাদেশের প্রথম কম্পিউটার প্রোগ্রামার কে ?',
            answer: 'হাফিজউদ্দিন মিয়া',
          },
          {
            id: 39,
            questionNo: '৩৯',
            question: 'বাংলাদেশের মোট আয়তন কত বর্গ কি.মি.?',
            answer: '১,৪৭,৬১০ বর্গ কি.মি.',
          },
          {
            id: 40,
            questionNo: '৪০',
            question: 'বাংলাদেশের পঞ্চম কৃষি বিশ্ববিদ্যালয় কোনটি?',
            answer: 'খুলনা কৃষি বিশ্ববিদ্যালয়',
          },
          {
            id: 41,
            questionNo: '৪১',
            question: 'তুলা চাষের জন্য বেশি উপযোগী কোন জেলা?',
            answer: 'যশোর।',
          },
          {
            id: 42,
            questionNo: '৪২',
            question: 'জাতীয় কৃষি দিবস কবে?',
            answer: 'পহেলা অগ্রহায়ন।',
          },
          {
            id: 43,
            questionNo: '৪৩',
            question: 'সারা দেশে নিবন্ধন কৃত কৃষকের সংখ্যা কত?',
            answer: 'এক কোটি আশি লাখ।',
          },
          {
            id: 44,
            questionNo: '৪৪',
            question: 'বাংলাদেশে আন্তর্জাতিক বিমান বন্দর কয়টি?',
            answer: 'তিন টি (ঢাকা, চট্রগ্রাম, সিলেট)।',
          },
          {
            id: 45,
            questionNo: '৪৫',
            question: 'স্বাধীনতার পর বাংলাদেশে প্রথম আদমশুমারি হয় কত সালে?',
            answer: '১৯৭৪ সালে।',
          },
          {
            id: 46,
            questionNo: '৪৬',
            question: 'BPL শুরু হয় কবে থেকে?',
            answer: '১০ ফেব্রুয়ারি ২০১২।',
          },
          {
            id: 47,
            questionNo: '৪৭',
            question: 'বাংলাদেশের মানচিত্র প্রথম আঁকেন কে?',
            answer: 'মেজর জেমস রেনেল।',
          },
          {
            id: 48,
            questionNo: '৪৮',
            question: 'বাংলাদেশের জাতীয় পতাকার অনুপাত কত?',
            answer: '১০ঃ৬ বা ৫ঃ৩।',
          },
          {
            id: 49,
            questionNo: '৪৯',
            question: 'বাংলাদেশের প্রধান সমুদ্র বন্দর কোনটি?',
            answer: 'চট্টগ্রাম।',
          },
          {
            id: 50,
            questionNo: '৫০',
            question: 'বাংলাদেশের জাতীয় পতাকার ডিজাইনার কে?',
            answer: 'কামরুল হাসান।',
          },
          {
            id: 51,
            questionNo: '২১',
            question:
              'বাংলাদেশে বর্তমানে পাবলিক বিশ্ববিদ্যালয়ের সংখ্যা কয়টি?',
            answer: '৫০ টি।',
          },
          {
            id: 52,
            questionNo: '২২',
            question: 'লালবাগ কেল্লা নির্মাণ করেন কে?',
            answer: 'শায়েস্তা খান।',
          },
          {
            id: 53,
            questionNo: '৫৩',
            question: 'ক্রিকেটে কত সালে বাংলাদেশ টেস্ট মর্যাদা পায়?',
            answer: '২৬ জুন ২০০০ সালে।',
          },
          {
            id: 54,
            questionNo: '৫৪',
            question: 'মুজিব নগর কোথায় অবস্থিত?',
            answer: 'মেহেরপুরে।',
          },
          {
            id: 55,
            questionNo: '৫৫',
            question: 'মুক্তিযুদ্ধের সময় মোট কতটি সেক্টর ছিল?',
            answer: '১১টি সেক্টর।',
          },
          {
            id: 56,
            questionNo: '৫৬',
            question: 'বাংলাদেশের জাতীয় সংসদের আসন কয়টি?',
            answer: '৩৫০টি',
          },
          {
            id: 57,
            questionNo: '৫৭',
            question: 'বাংলাদেশের সর্ববৃহৎ জেলা কোনটি?',
            answer: 'রাঙ্গামাটি',
          },
          {
            id: 58,
            questionNo: '৫৮',
            question: 'বাংলাদেশের পোশাক খাতের প্রধান বৈদেশিক বাজার কোন দেশ?',
            answer: 'যুক্তরাষ্ট্র',
          },
          {
            id: 59,
            questionNo: '৫৯',
            question: 'নির্মাণাধীন পদ্মা সেতুর দৈর্ঘ্য কত হবে?',
            answer: '৬.১৫ কি.মি',
          },
          {
            id: 60,
            questionNo: '৬০',
            question: 'লালন ফকিরের জন্মস্থান কোথায়?',
            answer: 'কুষ্টিয়া',
          },
          {
            id: 61,
            questionNo: '৬১',
            question:
              'বাংলাদেশের প্রথম পারমাণবিক বিদ্যুৎ কেন্দ্র কোথায় স্থাপিত হচ্ছে?',
            answer: 'পাবনা',
          },
          {
            id: 62,
            questionNo: '৬২',
            question: 'ম্যানগ্রোভ কি?',
            answer: 'উপকূলীয় বন',
          },
        ],
        total: '৬২',
      },
      {
        quiz: false,
        subject: false,
        question: true,
        subjectNo: '০২',
        title: 'বাংলাদেশের কৃষি',
        questionAndAnswer: [
          {
            id: 1,
            questionNo: '০১',
            question: 'কৃষি কাজের জন্য সর্বাপেক্ষা উপযোগী মাটি--',
            answer: 'পলি মাটি।',
          },
          {
            id: 2,
            questionNo: '০২',
            question: 'বাংলাদেশে ধান প্রধানত চার  শেণীর',
            answer: 'আউশ, আমন, বোরো ও ইরি।',
          },
          {
            id: 3,
            questionNo: '০৩',
            question: 'বাংলাদেশের কত ভাগ জমিতে পাট চাষ করা হয়',
            answer: '৭%।',
          },
          {
            id: 4,
            questionNo: '০৪',
            question: 'বাংলাদেশের সবচেয়ে বেশি রেশম গুটির চাষ হয়-',
            answer: 'চাঁপাইনবাবগঞ্জ।',
          },
          {
            id: 5,
            questionNo: '০৫',
            question: 'সবচেয়ে বেশী পাট উৎপন্ন হয়---',
            answer: 'ময়মনসিংহ জেলায় ।',
          },
          {
            id: 6,
            questionNo: '০৬',
            question: 'রবি শস্য বলতে বুঝায়',
            answer: 'শীতকালীন শস্যকে।',
          },
          {
            id: 7,
            questionNo: '০৭',
            question: 'খরিপ শস্য বলতে বুঝায়---',
            answer: 'গ্রীষ্মকালীন শস্যকে।',
          },
          {
            id: 8,
            questionNo: '০৮',
            question: 'বাংলাদেশের অর্থনীতিতে কৃষিখাতের অবদান--',
            answer: '২১.৯১%।',
          },
          {
            id: 9,
            questionNo: '০৯',
            question: 'বাংলাদেশের শস্য ভান্ডার বলা হয়---',
            answer: 'বরিশাল জেলাকে।',
          },
          {
            id: 10,
            questionNo: '১০',
            question: 'বাংলাদেশে বানিজ্যিকভাবে প্রথম চা চাষ করা হয়-',
            answer: '১৯৫৪ সালে।',
          },
          {
            id: 11,
            questionNo: '১১',
            question: 'গম গবেষণা কেন্দ্র কোন জেলায় অবস্থিত-',
            answer: 'দিনাজপুর।',
          },
          {
            id: 12,
            questionNo: '১২',
            question: 'বাংলাদেশে সবচেবে গম বেশি উৎপাদন হয়-',
            answer: 'রংপুর জেলায়।',
          },
          {
            id: 13,
            questionNo: '১৩',
            question: 'বাংলদেশের প্রথম চা বাগান কোনটি-',
            answer: 'সিলেটের মালনিছড়া।',
          },
          {
            id: 14,
            questionNo: '১৪',
            question: 'সবচেয়ে বেশী চা জন্মে কোন জেলায়---',
            answer: 'মৌলভীবাজার জেলায়।',
          },
          {
            id: 15,
            questionNo: '১৫',
            question: 'বাংলাদেশের মোট কৃষি জমির পরিমান-',
            answer: '২,০৪,৮৪,৫৬১ একর।',
          },
          {
            id: 16,
            questionNo: '১৬',
            question: 'বাংলাদেশের মোট চাষাবাদযোগ্য জমির পরিমান কত-',
            answer: '১,৭৭,৭১,৩৩৯ একর ৷',
          },
          {
            id: 17,
            questionNo: '১৭',
            question: 'বাংলাদেশে চাষের অযোগ্য চাষের জমির পরিমান-',
            answer: '২৭,১৩,২২২ একর।',
          },
          {
            id: 18,
            questionNo: '১৮',
            question: 'বাংলাদেশের প্রধান অর্থকরী ফসল---',
            answer: 'পাট।',
          },
          {
            id: 19,
            questionNo: '১৯',
            question: 'বাংলাদেশের দ্বিতীয় অর্থকরী ফসল-',
            answer: 'চা।',
          },
          {
            id: 20,
            questionNo: '২০',
            question: 'বিশ্বে ধান উৎপাদনে বাংলাদেশের অবস্থান-',
            answer: 'চতুর্থ।',
          },
          {
            id: 21,
            questionNo: '২১',
            question: 'পাট উৎপাদনে বিশ্বে বাংলাদেশের স্থান',
            answer: 'প্রথম।  ',
          },
          {
            id: 22,
            questionNo: '২২',
            question: 'বাংলাদেশের চা গবেষণা কেন্দ্র কোথায় অবস্থিত-',
            answer: 'মৌলভীবাজার জেলার শ্রীমঙ্গলে। ',
          },
          {
            id: 23,
            questionNo: '২৩',
            question: 'বাংলাদেশে মোট চা বাগানের সংখ্যা কত-',
            answer: '১৫৯ টি।',
          },
          {
            id: 24,
            questionNo: '২৪',
            question: 'বাংলাদেশের সবচেয়ে বেশী রেশম উৎপন্ন হয়-',
            answer: 'চাঁপাই নবাবগঞ্জে। ',
          },
          {
            id: 25,
            questionNo: '২৫',
            question: 'বাংলাদেশ রেশম বোর্ড অবস্থিত',
            answer: 'চাঁপাই নবাবগঞ্জে।',
          },
          {
            id: 26,
            questionNo: '২৬',
            question: 'বাংলাদেশে সবচেয়ে বেশী তামাক জন্মে',
            answer: 'রংপুরে। ',
          },
          {
            id: 27,
            questionNo: '২৭',
            question: 'বাংলাদেশে সবচেয়ে বেশী তুলা জন্মে---',
            answer: 'যশোরে।',
          },
          {
            id: 28,
            questionNo: '২৮',
            question: 'বাংলাদেশের সবচেয়ে বড় সেচ প্রকল্প',
            answer: 'তিস্তা বাধ প্রকল্প।',
          },
          {
            id: 29,
            questionNo: '২৯',
            question: 'বাংলাদেশে ধান গবেষনাকেন্দ্র কোথায়-',
            answer: 'গাজিপুর। ',
          },
          {
            id: 30,
            questionNo: '৩০',
            question: 'বাংলাদেশে মাথাপিছু আবাদী জমির পরিমান-',
            answer: '০.১৪ একর।  ',
          },
          {
            id: 31,
            questionNo: '৩১',
            question: 'বাংলাদেশ কৃষি গবেষণা ইনষ্টিটিউট কবে প্রতিষ্ঠিত হয়-',
            answer: '১৯৭১ সালে।',
          },
          {
            id: 32,
            questionNo: '৩২',
            question: 'ঢাকা চিড়িয়াখানা প্রস্তাবিত নতুন নাম-',
            answer: 'বাংলাদেশ জাতীয় চিড়িয়াখানা।',
          },
          {
            id: 33,
            questionNo: '৩৩',
            question: 'পরিবেশের যে দূষনের ফলে প্রধানত উচ্চ রক্তচাপ হতে পারে-',
            answer: 'শব্দ দূষণ।',
          },
          {
            id: 34,
            questionNo: '৩৪',
            question: 'বৈদ্যুতিক ইস্ত্রি এবং হিটারে ব্যবহৃত হয়-',
            answer: 'নাইক্রোম তার ।',
          },
          {
            id: 35,
            questionNo: '৩৫',
            question: 'তড়িৎ শক্তি শব্দ শক্তিতে রূপান্তরিত করে-',
            answer: 'লাউড স্পিকার।',
          },
          // {
          //   id: 36,
          //   questionNo: '৩৬',
          //   question: 'question',
          //   answer: 'answer',
          // },
          // {
          //   id: 37,
          //   questionNo: '৩৭',
          //   question: 'question',
          //   answer: 'answer',
          // },
          // {
          //   id: 38,
          //   questionNo: '৩৮',
          //   question: 'question',
          //   answer: 'answer',
          // },
          // {
          //   id: 39,
          //   questionNo: '৩৯',
          //   question: 'question',
          //   answer: 'answer',
          // },
          // {
          //   id: 40,
          //   questionNo: '৪০',
          //   question: 'question',
          //   answer: 'answer',
          // },
          // {
          //   id: 41,
          //   questionNo: '৪১',
          //   question: 'question',
          //   answer: 'answer',
          // },
          // {
          //   id: 42,
          //   questionNo: '৪২',
          //   question: 'question',
          //   answer: 'answer',
          // },
          // {
          //   id: 43,
          //   questionNo: '৪৩',
          //   question: 'question',
          //   answer: 'answer',
          // },
          // {
          //   id: 44,
          //   questionNo: '৪৪',
          //   question: 'question',
          //   answer: 'answer',
          // },
          // {
          //   id: 45,
          //   questionNo: '৪৫',
          //   question: 'question',
          //   answer: 'answer',
          // },
          // {
          //   id: 46,
          //   questionNo: '৪৬',
          //   question: 'question',
          //   answer: 'answer',
          // },
          // {
          //   id: 47,
          //   questionNo: '৪৭',
          //   question: 'question',
          //   answer: 'answer',
          // },
          // {
          //   id: 48,
          //   questionNo: '৪৮',
          //   question: 'question',
          //   answer: 'answer',
          // },
          // {
          //   id: 49,
          //   questionNo: '৪৯',
          //   question: 'question',
          //   answer: 'answer',
          // },
          // {
          //   id: 50,
          //   questionNo: '৫০',
          //   question: 'question',
          //   answer: 'answer',
          // },
          // {
          //   id: 51,
          //   questionNo: '২১',
          //   question: 'question',
          //   answer: 'answer',
          // },
          // {
          //   id: 52,
          //   questionNo: '২২',
          //   question: 'question',
          //   answer: 'answer',
          // },
          // {
          //   id: 53,
          //   questionNo: '৫৩',
          //   question: 'question',
          //   answer: 'answer',
          // },
          // {
          //   id: 54,
          //   questionNo: '৫৪',
          //   question: 'question',
          //   answer: 'answer',
          // },
          // {
          //   id: 55,
          //   questionNo: '৫৫',
          //   question: 'question',
          //   answer: 'answer',
          // },
          // {
          //   id: 56,
          //   questionNo: '৫৬',
          //   question: 'question',
          //   answer: 'answer',
          // },
          // {
          //   id: 57,
          //   questionNo: '৫৭',
          //   question: 'question',
          //   answer: 'answer',
          // },
          // {
          //   id: 58,
          //   questionNo: '৫৮',
          //   question: 'question',
          //   answer: 'answer',
          // },
          // {
          //   id: 59,
          //   questionNo: '৫৯',
          //   question: 'question',
          //   answer: 'answer',
          // },
          // {
          //   id: 60,
          //   questionNo: '৬০',
          //   question: 'question',
          //   answer: 'answer',
          // },
        ],
        total: '৩৫',
      },
      {
        quiz: false,
        subject: false,
        question: true,
        subjectNo: '০৩',
        title: 'আন্তর্জাতিক বিষয়াবলী',
        questionAndAnswer: [
          {
            id: 1,
            questionNo: '০১',
            question: 'বাংলাদেশের রাষ্ট্রীয় প্রতীকের ডিজাইনার কে?',
            answer: 'শিল্পী কামরুল হাসান।',
          },
          {
            id: 2,
            questionNo: '০২',
            question: 'বাংলাদেশের সাংবিধানিক নাম কি?',
            answer: 'গণপ্রজাতন্ত্রী বাংলাদেশ।',
          },
          {
            id: 3,
            questionNo: '০৩',
            question:
              'বাংলাদেশের মুক্তিযুদ্ধে ‘বীর প্রতীক’ খেতাবপ্রাপ্ত একমাত্র বিদেশি নাগরিক কে?',
            answer: 'উইলিয়াম এ এস ওডারল্যান্ড।',
          },
          {
            id: 4,
            questionNo: '০৪',
            question: 'জাতিসংঘ শান্তিরক্ষা মিশন কত সালে নোবেল পায়?',
            answer: '১৯৮৮ সালে।',
          },
          {
            id: 5,
            questionNo: '০৫',
            question: 'পৃথিবীর বৃহত্তম দ্বীপ এর নাম কি?',
            answer: 'গ্রিনল্যান্ড (২১,৩০,৮০০ বর্গ কিলোমিটার)',
          },
          {
            id: 6,
            questionNo: '০৬',
            question: 'স্বাধীন বাংলা বেতার কেন্দ্র প্রথম কোথায় স্থাপিত হয়েছিল?',
            answer: 'কালুরঘাট, চট্টগ্রাম।',
          },
          {
            id: 7,
            questionNo: '০৭',
            question: 'স্বাধীন বাংলা বেতার কেন্দ্র থেকে চরমপত্র পাঠ করতেন কে?',
            answer: 'এম আর আখতার মুকুল।',
          },
          {
            id: 8,
            questionNo: '০৮',
            question: 'দ্বিতীয় বিশ্বযুদ্ধ কবে শুরু হয়?',
            answer: '১৯৩৯ সালে।',
          },
          {
            id: 9,
            questionNo: '০৯',
            question: 'ATM-এর জনক কে?',
            answer: 'জন শেফার্ড ব্যারন।',
          },
          {
            id: 10,
            questionNo: '১০',
            question: 'দক্ষিণ সুদান স্বাধীন হয় কত সালে?',
            answer: '২০১১ সালে।',
          },
          {
            id: 11,
            questionNo: '১১',
            question: 'জাপানের বৃহত্তম দ্বীপ এর নাম কী?',
            answer: 'হনসু।',
          },
          {
            id: 12,
            questionNo: '১২',
            question: 'দ্বীপদেশ ব্রুনাইয়ের রাজধানীর নাম কী?',
            answer: 'বন্দর সেরি বেগাওয়ান।',
          },
          {
            id: 13,
            questionNo: '১৩',
            question: 'জাতিসংঘ প্রতিষ্ঠিত হয় কবে?',
            answer: '১৯৪৫ সালে।',
          },
          {
            id: 14,
            questionNo: '১৪',
            question: 'কনসার্ট ফর বাংলাদেশ-এর প্রধান শিল্পী কে?',
            answer: 'জর্জ হ্যারিসন।',
          },
          {
            id: 15,
            questionNo: '১৫',
            question: 'চির শান্তির শহর বলা হয় কোন শহর কে?',
            answer: 'রোম শহরকে।',
          },
          {
            id: 16,
            questionNo: '১৬',
            question: 'এ পি জে আব্দুল কালাম মারা যান কত সালে?',
            answer: '২০১৫ সালে।',
          },
          {
            id: 17,
            questionNo: '১৭',
            question: 'ছিয়াত্তরের মন্বন্তর হয় বাংলা কত সালে?',
            answer: '১১৭৬ সালে।',
          },
          {
            id: 18,
            questionNo: '১৮',
            question: 'গণপ্রজাতন্ত্রী বাংলাদেশের সংবিধানে মোট কতটি তফসিল আছে',
            answer: 'সাতটি।',
          },
          {
            id: 19,
            questionNo: '১৯',
            question: 'সুয়েজ খাল জাতীয়করণ হয় কত সালে?',
            answer: '১৯৫৬ সালে।',
          },
          {
            id: 20,
            questionNo: '২০',
            question: 'বাংলাদেশে কোন ভূমিরূপটি দেখা যায় না?',
            answer: 'মালভূমি।',
          },
          {
            id: 21,
            questionNo: '২১',
            question: 'বিবিসি বাংলার যাত্রা শুরু হয় কত সালে?',
            answer: '১৯৪১ সালে।',
          },
          {
            id: 22,
            questionNo: '২২',
            question: 'WWW মানে কি?',
            answer: 'World Wide Web',
          },
          {
            id: 23,
            questionNo: '২৩',
            question: 'বাংলাদেশের কোন জেলাকে প্রকৃতির রানি বলা হয়?',
            answer: 'খাগড়াছড়ি জেলাকে।',
          },
          {
            id: 24,
            questionNo: '২৪',
            question: 'ঢাকা বিশ্ববিদ্যালয় প্রতিষ্ঠিত হয় কত সালে?',
            answer: '১৯২১ সালে।',
          },
          {
            id: 25,
            questionNo: '২৫',
            question: '‘সেপ্টেম্বর অন যশোর রোড’ কবিতাটির রচয়িতা কে?',
            answer: 'অ্যালেন গিনসবার্গ।',
          },
          {
            id: 26,
            questionNo: '২৬',
            question: 'সাঙ্গু ভ্যালি কোথায়?',
            answer: 'চট্টগ্রামে।',
          },
          {
            id: 27,
            questionNo: '২৭',
            question: 'মাইনমুখী ভ্যালি কোন জেলায়?',
            answer: 'রাঙামাটি জেলায়।',
          },
          {
            id: 28,
            questionNo: '২৮',
            question: 'কাপ্তাই লেকে প্লাবিত উপত্যকার নাম কী?',
            answer: 'ভেঙ্গি ভ্যালি।',
          },
          {
            id: 29,
            questionNo: '২৯',
            question: 'রাঙামাটির ছাদ বলা হয় কোন জায়গাকে?',
            answer: 'সাজেক ভ্যালিকে।',
          },
          {
            id: 30,
            questionNo: '৩০',
            question: 'পাহাড়ি কন্যা বলা হয় বাংলাদেশের কোন জেলাকে?',
            answer: 'বান্দরবান জেলাকে।',
          },
          {
            id: 31,
            questionNo: '৩১',
            question: '১৯৭১ সালে মুক্তিযুদ্ধের সময় জাতিসংঘের মহাসচিব কে ছিলেন?',
            answer: 'উ থান্ট।',
          },
          {
            id: 32,
            questionNo: '৩২',
            question:
              'বাংলাদেশের মুক্তিযুদ্ধের সময় আমেরিকার প্রেসিডেন্ট কে ছিলেন?',
            answer: 'রিচার্ড নিক্সন।',
          },
          {
            id: 33,
            questionNo: '৩৩',
            question:
              'বাংলাদেশের মুক্তিযুদ্ধে নিহত মাদার মারিও ভেরেনজি কোন দেশের নাগরিক ছিলেন?',
            answer: 'ইতালির নাগরিক।',
          },
          {
            id: 34,
            questionNo: '৩৪',
            question: 'বাংলাদেশের ফুসফুস বলা হয় কাকে?',
            answer: 'সুন্দরবনকে',
          },
          {
            id: 35,
            questionNo: '৩৫',
            question:
              'বাংলাদেশের মুক্তিযুদ্ধের সময় ভারতের প্রধানমন্ত্রী কে ছিলেন?',
            answer: 'ইন্দিরা গান্ধী।',
          },
          {
            id: 36,
            questionNo: '৩৬',
            question: 'বাংলাদেশ সশস্ত্র বাহিনী দিবস কবে?',
            answer: '২১ নভেম্বর।',
          },
          {
            id: 37,
            questionNo: '৩৭',
            question: 'আবু মুসা দ্বীপ কোন সাগরে?',
            answer: 'পারস্য উপসাগরে।',
          },
          {
            id: 38,
            questionNo: '৩৮',
            question: 'ভারত মহাসাগরের কোন দ্বীপ আয়তনে সবচেয়ে বড়?',
            answer: 'মাদাগাস্কার।',
          },
          {
            id: 39,
            questionNo: '৩৯',
            question: 'ওকিনাওয়া দ্বীপ কোন দেশের নিয়ন্ত্রণাধীন?',
            answer: 'জাপান।',
          },
          {
            id: 40,
            questionNo: '৪০',
            question: 'আগুনের দ্বীপ বলা হয় কাকে?',
            answer: 'আইসল্যান্ড দ্বীপকে।',
          },
          {
            id: 41,
            questionNo: '৪১',
            question: '‘ম্যাপল পাতার দেশ’ কোন দেশের উপনাম?',
            answer: 'কানাডা।',
          },
          {
            id: 42,
            questionNo: '৪২',
            question: 'শিকাগো শহরকে কি বলা হয়?',
            answer: 'বাতাসের শহর।',
          },
          {
            id: 43,
            questionNo: '৪৩',
            question: 'আধুনিক শিক্ষার জনক কে?',
            answer: 'সক্রেটিস।',
          },
          {
            id: 44,
            questionNo: '৪৪',
            question: 'বাংলাদেশের প্রথম এভারেস্টজয়ী নারী কে?',
            answer: 'নিশাত মজুমদার।',
          },
          {
            id: 45,
            questionNo: '৪৫',
            question: 'পদ্মা নদীর উৎপত্তিস্থল কোথায়?',
            answer: 'গঙ্গোত্রী হিমবাহ।',
          },
          {
            id: 46,
            questionNo: '৪৬',
            question: 'গরম পানির ঝরনা কোথায় অবস্থিত?',
            answer: 'সীতাকুণ্ড।',
          },
          {
            id: 47,
            questionNo: '৪৭',
            question: 'বিশ্বসেরা মুষ্টিযোদ্ধা মোহাম্মদ আলী মারা যান কত সালে?',
            answer: '২০১৬ সালে।',
          },
          {
            id: 48,
            questionNo: '৪৮',
            question: 'বাংলাদেশের আমাজান বলা কাকে?',
            answer: 'সিলেটের রাতারগুল বনকে।',
          },
          {
            id: 49,
            questionNo: '৪৯',
            question: 'কোন দেশ ভাটির দেশ নামে পরিচিত?',
            answer: 'বাংলাদেশ।',
          },
          {
            id: 50,
            questionNo: '৫০',
            question: 'গণপ্রজাতন্ত্রী বাংলাদেশের সর্বোচ্চ আইন কী?',
            answer: 'সংবিধান।',
          },
          {
            id: 51,
            questionNo: '২১',
            question: 'বাংলাদেশ সংবিধান দুষ্পরিবর্তনীয় কেন?',
            answer: 'পরিবর্তন সহজ নয় বলে।',
          },
          {
            id: 52,
            questionNo: '২২',
            question: 'বাংলাদেশের সংবিধানে কয়টি ভাগ (অধ্যায়) আছে?',
            answer: '১১টি।',
          },
          {
            id: 53,
            questionNo: '৫৩',
            question: 'গণপ্রজাতন্ত্রী বাংলাদেশের সংবিধানে কতটি অনুচ্ছেদ আছে?',
            answer: '১৫৩টি।',
          },
          {
            id: 54,
            questionNo: '৫৪',
            question: '৩৬০ আউলিয়ার দেশ বলা হয় বাংলাদেশের কোন জেলাকে?',
            answer: 'সিলেট।',
          },
          {
            id: 55,
            questionNo: '৫৫',
            question: '১২ আউলিয়ার দেশ বলা হয় কোন জেলাকে?',
            answer: 'চট্টগ্রাম।',
          },
          {
            id: 56,
            questionNo: '৫৬',
            question: 'গুগলের প্রতিষ্ঠাতা কে?',
            answer: 'ল্যারি পেজ ও সার্গেই ব্রিন।',
          },
          {
            id: 57,
            questionNo: '৫৭',
            question: 'প্রকৃতির কন্যা বলা হয় কাকে?',
            answer: 'সিলেটের জাফলংকে।',
          },
          {
            id: 58,
            questionNo: '৫৮',
            question: 'question',
            answer: 'answer',
          },
          {
            id: 59,
            questionNo: '৫৯',
            question: 'মার্কেটিংয়ের জনক কে?',
            answer: 'ফিলিপ কটলার।',
          },
          {
            id: 60,
            questionNo: '৬০',
            question: 'এনাটমির জনক কে?',
            answer: 'আঁদ্রে ভেসালিয়াস।',
          },
          {
            id: 61,
            questionNo: '৬১',
            question: 'সর্বাধিক ভাষার দেশ কোনটি?',
            answer: 'পাপুয়া নিউগিনি।',
          },
          {
            id: 62,
            questionNo: '৬২',
            question: 'আধুনিক ল্যাপটপের জনক কে?',
            answer: 'বাল মেগারিজ।',
          },
          {
            id: 63,
            questionNo: '৬৩',
            question: 'নিষিদ্ধ শহর বলা হয় কাকে?',
            answer: 'তিব্বতকে',
          },
          {
            id: 64,
            questionNo: '৬৪',
            question: 'মুক্তার দেশ বলা হয় কাকে?',
            answer: 'কিউবা।',
          },
          {
            id: 65,
            questionNo: '৬৫',
            question: 'ইন্টারনেটের জনক কে?',
            answer: 'ভিনটন জি কার্ফ।',
          },
          {
            id: 66,
            questionNo: '৬৬',
            question: 'ই-মেইলের জনক কে?',
            answer: 'রে টমলিনসন।',
          },
          {
            id: 67,
            questionNo: '৬৭',
            question: '‘বলিশিরা ভ্যালি’ কোন জেলায় অবস্থিত?',
            answer: 'মৌলভীবাজার জেলায়।',
          },
          {
            id: 68,
            questionNo: '৬৮',
            question: 'হালদা ভ্যালি কোথায় অবস্থিত?',
            answer: 'খাগড়াছড়ি।',
          },
          {
            id: 69,
            questionNo: '৬৯',
            question: '‘রয়টার্স’-এর প্রতিষ্ঠাতা কে?',
            answer: 'পল জুলিয়াস রয়টার',
          },
          {
            id: 70,
            questionNo: '৭০',
            question: '‘রয়টার্স’ কোন দেশের সংবাদ সংস্থা?',
            answer: 'যুক্তরাজ্য।',
          },
          {
            id: 71,
            questionNo: '৭১',
            question: 'নাপিতখালী ভ্যালি কোথায় অবস্থিত?',
            answer: 'কক্সবাজার।',
          },
          {
            id: 72,
            questionNo: '৭২',
            question:
              'মার্ক জাকারবার্গ ও তাঁর ৩ সহপাঠী কতসালে ফেসবুক প্রতিষ্ঠা করেন?',
            answer: '২০০৪ সালে।',
          },
          {
            id: 73,
            questionNo: '৭৩',
            question: 'হিমালয়ের কন্যা বলা হয় কোন জেলাকে ?',
            answer: 'পঞ্চগড়কে।',
          },
          {
            id: 74,
            questionNo: '৭৪',
            question: 'আধুনিক ফিন্যান্সের জনক কে?',
            answer: 'ড. ইউগেন ফামা।',
          },
          {
            id: 75,
            questionNo: '৭৫',
            question: 'কোন গাছকে সূর্যকন্যা বলা হয়?',
            answer: 'তুলা গাছকে।',
          },
          {
            id: 76,
            questionNo: '৭৬',
            question: 'ভূমধ্যসাগরের বাতিঘর বলা হয় কোন আগ্নেয়গিরিকে?',
            answer: 'স্ট্রম্বোলি।',
          },
          {
            id: 77,
            questionNo: '৭৭',
            question: 'প্রাচ্যের ডান্ডি হিসেবে পরিচিত বাংলাদেশের কোন জেলা?',
            answer: 'নারায়ণগঞ্জ।',
          },
          {
            id: 78,
            questionNo: '৭৮',
            question: 'বাংলাদেশের প্রবেশদ্বার বলা হয় কোন জেলাকে?',
            answer: 'চট্টগ্রামকে',
          },
          {
            id: 79,
            questionNo: '৭৯',
            question: 'বাংলাদেশে শীতল পানির ঝরনা কোথায় অবস্থিত?',
            answer: 'কক্সবাজার।',
          },
          {
            id: 80,
            questionNo: '৮০',
            question:
              'বাংলার ভেনিস তথা বাংলার শস্যভাণ্ডার হিসেবে পরিচিত কোন জেলা?',
            answer: 'বরিশাল।',
          },
          {
            id: 81,
            questionNo: '৮১',
            question: 'সৌন্দর্যের লীলাভূমি বলা হয় কোন জেলাকে?',
            answer: 'রাঙামাটিকে।',
          },
          {
            id: 82,
            questionNo: '৮২',
            question: 'বাংলাদেশের দ্বীপের রানি বলা হয় কোন জেলাকে?',
            answer: 'ভোলা জেলাকে',
          },
        ],
        total: '৮২',
      },
    ],
    total: '০৩',
  },
  {
    title: 'বিজ্ঞান বিষয়ক',
    quiz: false,
    subject: false,
    question: true,
    img: require('../assets/images/microscope.png'),
    questionAndAnswer: [
      {
        id: 1,
        questionNo: '০১',
        question: 'কোন রঙের কাপে চা তাড়াতাড়ি ঠান্ডা হয়',
        answer: 'কালো।',
      },
      {
        id: 2,
        questionNo: '০২',
        question: 'মটরগাড়ির হেড লাইটে কোন দর্পন ব্যবহার করা হয়',
        answer: 'অবতল।',
      },
      {
        id: 3,
        questionNo: '০৩',
        question:
          'রান্না করার হাড়িপাতিল সাধারণত এলুমেনিয়াম ব্যবহার করা হয় কারণ',
        answer: 'এতে দ্রুত তাপ সঞ্চালিত হয়ে খাদ্যদ্রব্য তাড়াতাড়ি সিদ্ধ হয়।',
      },
      {
        id: 4,
        questionNo: '০৪',
        question: 'পৃথিবীর ঘূর্ণনের ফলে আমরা ছিটকে পড়ি না কেন',
        answer: 'মধ্যাকর্ষণ বলের জন্য।',
      },
      {
        id: 5,
        questionNo: '০৫',
        question: 'কোন মাধ্যমে শব্দের গতি সবচেয়ে বেশি',
        answer: 'কঠিন।',
      },
      {
        id: 6,
        questionNo: '০৬',
        question: 'একক সময়ে শব্দ যে দুরত্ব অতিক্রম করে তাকে বলে',
        answer: 'শব্দের গতি।',
      },
      {
        id: 7,
        questionNo: '০৭',
        question:
          'বিদ্যুৎ পরিবাহী তাপমাত্রা ও প্রস্থচ্ছেদ অপরিবর্তিত থাকলে দৈর্ঘ্য বাড়ালে রোধে কি ঘটবে',
        answer: 'রোধ বাড়বে।',
      },
      {
        id: 8,
        questionNo: '০৮',
        question: 'লাল ও সবুজ রং মিশিয়ে কোন রং পাওয়া যায়',
        answer: 'হলুদ।',
      },
      {
        id: 9,
        questionNo: '০৯',
        question:
          'সূর্য থেকে হঠাৎ আলো আসা বন্ধ হয়ে গেলে তা আমরা অনুভব করতে পারি কতক্ষণ পর',
        answer: '8 মিনিট 32 সেকেন',
      },
      {
        id: 10,
        questionNo: '১০',
        question: 'ছাতার কাপড়ের রং সাধারণ কালো হয় কেন',
        answer: 'কালো রং তাপ শোষন করে বলে।',
      },
      {
        id: 11,
        questionNo: '১১',
        question: 'একজন মানুষ কি অবস্থায় পৃথিবীকে সবচেয়ে কম চাপ দেয়',
        answer: 'শোয়া অবস্থায়।',
      },
      {
        id: 12,
        questionNo: '১২',
        question: 'ন্যানো সেকেন্ড হলো',
        answer: 'এক সেকেন্ডের একশত কোটি ভাগের একভাগ।',
      },
      {
        id: 13,
        questionNo: '১৩',
        question: 'শূন্য ঘরের চেয়ে লোক ভর্তি ঘরের শব্দ কম হয় কেন',
        answer: 'শূন্য ঘরে শব্দের শোষণ কম হয়।',
      },
      {
        id: 14,
        questionNo: '১৪',
        question: 'পানিকে বরফে পরিনত করলে এর আয়তন',
        answer: 'বাড়ে।',
      },
      {
        id: 15,
        questionNo: '১৫',
        question: 'বর্ণান্ধ লোকেরা কোন রং বুঝতে পারে না',
        answer: 'লাল , নীল, সবুজ।',
      },
      {
        id: 16,
        questionNo: '১৬',
        question: 'ভূমি থেকে উপরে উঠলে শ্বাসকষ্ট হয় কেন',
        answer: 'উপরে বায়ুর চাপ বেশি থাকে।',
      },
      {
        id: 17,
        questionNo: '১৭',
        question: 'গ্রীষ্মকালে আমরা কালো কাপড় পরিধান করি না কেন',
        answer: 'কালো কাপড় শরীরের তাপ কে বাহিরে যেতে দেয় না।',
      },
      {
        id: 18,
        questionNo: '১৮',
        question: 'ফ্যান চালালে আমরা ঠান্ডা অনুভব করি কারন',
        answer: 'শরীর থেকে বাষ্পীভবনের হার বাড়িয়ে দেয়।',
      },
      {
        id: 19,
        questionNo: '১৯',
        question: '"শিমের বিচি" কোন ধরনের খাদ্য',
        answer: 'আমিষ।',
      },
      {
        id: 20,
        questionNo: '২০',
        question: 'কলার চারা লাগানোর সময় পাতা কেটে ফেলা হয় কেন',
        answer: 'প্রস্বেদন রোধ করার জন্য।',
      },
    ],
    total: '২০',
  },
  {
    title: 'অন্যান্য',
    quiz: false,
    subject: false,
    question: true,
    img: require('../assets/images/idea.png'),
    questionAndAnswer: [
      {
        id: 1,
        questionNo: '০১',
        question: 'সবচেয়ে ছোট পাখি কোনটি?',
        answer: 'হামিং বার্ড।',
      },
      {
        id: 2,
        questionNo: '০২',
        question: 'মৌমাছির চোখ কয়টি?',
        answer: '৫টি।',
      },
      {
        id: 3,
        questionNo: '০৩',
        question: 'মাকড়শার চোখ কয়টি?',
        answer: '৮টি।',
      },
      {
        id: 4,
        questionNo: '০৪',
        question: 'মাকড়শার পা কয়টি?',
        answer: '৮টি।',
      },
      {
        id: 5,
        questionNo: '০৫',
        question: 'মাছির পা কয়টি?',
        answer: '৬টি।',
      },
      {
        id: 6,
        questionNo: '০৬',
        question: 'সবচেয়ে দ্রুতগামী স্থলচর জন্তু কোনটি?',
        answer: 'চিতাবাঘ।',
      },
      {
        id: 7,
        questionNo: '০৭',
        question: 'মানব দেহে মোট কয়টি হাড় থাকে?',
        answer: '২০৬টি।',
      },
      {
        id: 8,
        questionNo: '০৮',
        question:
          'চার পায়ে বসি মোরা, আট পায়ে চলি। বাঘও নই ভাল্লুকও নই আস্ত কাঁধে ঝুলি। ',
        answer: 'পালকি।',
      },
      {
        id: 9,
        questionNo: '০৯',
        question: 'ব্যবহার করার জন্য কোন জিনিসটাকে ভাঙতেই হবে?',
        answer: 'ডিম। ',
      },
      {
        id: 10,
        questionNo: '১০',
        question: 'কোন জামা গাঁয়ে দেয় না?',
        answer: 'পায়জামা। ',
      },
      {
        id: 11,
        questionNo: '১১',
        question: 'কোন তরকারীতে লবন লাগে না?',
        answer: 'নোনা ইলিশ। ',
      },
      {
        id: 12,
        questionNo: '১২',
        question: 'কোন গাছে মাত্র দুই পাতা থাকে?',
        answer: 'চারাগাছ। ',
      },
      {
        id: 13,
        questionNo: '১৩',
        question: 'কোন জিনিসের নাম নিলেই সেটি ভেঙ্গে যায়?',
        answer: 'নীরবতা। ',
      },
      {
        id: 14,
        questionNo: '১৪',
        question:
          'কোন জিনিস একবার খেলে আর খেতে চান না, আপনাকে না জানিয়ে খাওয়ানো হয়। ',
        answer: 'ধোকা। ',
      },
      {
        id: 15,
        questionNo: '১৫',
        question: 'কি নামতে পারে, কিন্তু উঠতে পারে না?',
        answer: 'বৃষ্টি। ',
      },
      {
        id: 16,
        questionNo: '১৬',
        question: 'দশ দিন না ঘুমিয়ে থাকবেন কীকরে?',
        answer: 'রাতে ঘুমিয়ে নেবেন। ',
      },
      {
        id: 17,
        questionNo: '১৭',
        question: 'বাংলাদেশের জাতীয় দিবস কোনটি?',
        answer: '২৬ মার্চ',
      },
      {
        id: 18,
        questionNo: '১৮',
        question: 'কোন দেশকে ২ নীতির দেশ বলা হয়?',
        answer: 'চীন',
      },
      {
        id: 19,
        questionNo: '১৯',
        question: 'মাতৃভাষার সংখ্যা অনুসারে বাংলা ভাষার অবস্থান কত?',
        answer: 'পঞ্চম।',
      },
      {
        id: 20,
        questionNo: '২০',
        question: 'ব্যবহারকারীর দিক থেকে বাংলা ভাষার অবস্থান কত?',
        answer: ' সপ্তম।',
      },
    ],
    total: '২০',
  },
];

export default allQuestionsAndAnswers;

// islamicQuiz
// {
//     id: 1,
//     questionNo: '০১',
//     question: 'question',
//     answer: 'answer',
//   },
//   {
//     id: 2,
//     questionNo: '০২',
//     question: 'question',
//     answer: 'answer',
//   },
//   {
//     id: 3,
//     questionNo: '০৩',
//     question: 'question',
//     answer: 'answer',
//   },
//   {
//     id: 4,
//     questionNo: '০৪',
//     question: 'question',
//     answer: 'answer',
//   },
//   {
//     id: 5,
//     questionNo: '০৫',
//     question: 'question',
//     answer: 'answer',
//   },
//   {
//     id: 6,
//     questionNo: '০৬',
//     question: 'question',
//     answer: 'answer',
//   },
//   {
//     id: 7,
//     questionNo: '০৭',
//     question: 'question',
//     answer: 'answer',
//   },
//   {
//     id: 8,
//     questionNo: '০৮',
//     question: 'question',
//     answer: 'answer',
//   },
//   {
//     id: 9,
//     questionNo: '০৯',
//     question: 'question',
//     answer: 'answer',
//   },
//   {
//     id: 10,
//     questionNo: '১০',
//     question: 'question',
//     answer: 'answer',
//   },
//   {
//     id: 11,
//     questionNo: '১১',
//     question: 'question',
//     answer: 'answer',
//   },
//   {
//     id: 12,
//     questionNo: '১২',
//     question: 'question',
//     answer: 'answer',
//   },
//   {
//     id: 13,
//     questionNo: '১৩',
//     question: 'question',
//     answer: 'answer',
//   },
//   {
//     id: 14,
//     questionNo: '১৪',
//     question: 'question',
//     answer: 'answer',
//   },
//   {
//     id: 15,
//     questionNo: '১৫',
//     question: 'question',
//     answer: 'answer',
//   },
//   {
//     id: 16,
//     questionNo: '১৬',
//     question: 'question',
//     answer: 'answer',
//   },
//   {
//     id: 17,
//     questionNo: '১৭',
//     question: 'question',
//     answer: 'answer',
//   },
//   {
//     id: 18,
//     questionNo: '১৮',
//     question: 'question',
//     answer: 'answer',
//   },
//   {
//     id: 19,
//     questionNo: '১৯',
//     question: 'question',
//     answer: 'answer',
//   },
//   {
//     id: 20,
//     questionNo: '২০',
//     question: 'question',
//     answer: 'answer',
//   },
//   {
//     id: 21,
//     questionNo: '২১',
//     question: 'question',
//     answer: 'answer',
//   },
//   {
//     id: 22,
//     questionNo: '২২',
//     question: 'question',
//     answer: 'answer',
//   },
//   {
//     id: 23,
//     questionNo: '২৩',
//     question: 'question',
//     answer: 'answer',
//   },
//   {
//     id: 24,
//     questionNo: '২৪',
//     question: 'question',
//     answer: 'answer',
//   },
//   {
//     id: 25,
//     questionNo: '২৫',
//     question: 'question',
//     answer: 'answer',
//   },
//   {
//     id: 26,
//     questionNo: '২৬',
//     question: 'question',
//     answer: 'answer',
//   },
//   {
//     id: 27,
//     questionNo: '২৭',
//     question: 'question',
//     answer: 'answer',
//   },
//   {
//     id: 28,
//     questionNo: '২৮',
//     question: 'question',
//     answer: 'answer',
//   },
//   {
//     id: 29,
//     questionNo: '২৯',
//     question: 'question',
//     answer: 'answer',
//   },
//   {
//     id: 30,
//     questionNo: '৩০',
//     question: 'question',
//     answer: 'answer',
//   },
//  {
//     id: 31,
//     questionNo: '৩১',
//     question: 'question',
//     answer: 'answer',
//   },
//   {
//     id: 32,
//     questionNo: '৩২',
//     question: 'question',
//     answer: 'answer',
//   },
//   {
//     id: 33,
//     questionNo: '৩৩',
//     question: 'question',
//     answer: 'answer',
//   },
//   {
//     id: 34,
//     questionNo: '৩৪',
//     question: 'question',
//     answer: 'answer',
//   },
//   {
//     id: 35,
//     questionNo: '৩৫',
//     question: 'question',
//     answer: 'answer',
//   },
//   {
//     id: 36,
//     questionNo: '৩৬',
//     question: 'question',
//     answer: 'answer',
//   },
//   {
//     id: 37,
//     questionNo: '৩৭',
//     question: 'question',
//     answer: 'answer',
//   },
//   {
//     id: 38,
//     questionNo: '৩৮',
//     question: 'question',
//     answer: 'answer',
//   },
//   {
//     id: 39,
//     questionNo: '৩৯',
//     question: 'question',
//     answer: 'answer',
//   },
//   {
//     id: 40,
//     questionNo: '৪০',
//     question: 'question',
//     answer: 'answer',
//   },
//   {
//     id: 41,
//     questionNo: '৪১',
//     question: 'question',
//     answer: 'answer',
//   },
//   {
//     id: 42,
//     questionNo: '৪২',
//     question: 'question',
//     answer: 'answer',
//   },
//   {
//     id: 43,
//     questionNo: '৪৩',
//     question: 'question',
//     answer: 'answer',
//   },
//   {
//     id: 44,
//     questionNo: '৪৪',
//     question: 'question',
//     answer: 'answer',
//   },
//   {
//     id: 45,
//     questionNo: '৪৫',
//     question: 'question',
//     answer: 'answer',
//   },
//   {
//     id: 46,
//     questionNo: '৪৬',
//     question: 'question',
//     answer: 'answer',
//   },
//   {
//     id: 47,
//     questionNo: '৪৭',
//     question: 'question',
//     answer: 'answer',
//   },
//   {
//     id: 48,
//     questionNo: '৪৮',
//     question: 'question',
//     answer: 'answer',
//   },
//   {
//     id: 49,
//     questionNo: '৪৯',
//     question: 'question',
//     answer: 'answer',
//   },
//   {
//     id: 50,
//     questionNo: '৫০',
//     question: 'question',
//     answer: 'answer',
//   },
//   {
//     id: 51,
//     questionNo: '২১',
//     question: 'question',
//     answer: 'answer',
//   },
//   {
//     id: 52,
//     questionNo: '২২',
//     question: 'question',
//     answer: 'answer',
//   },
//   {
//     id: 53,
//     questionNo: '৫৩',
//     question: 'question',
//     answer: 'answer',
//   },
//   {
//     id: 54,
//     questionNo: '৫৪',
//     question: 'question',
//     answer: 'answer',
//   },
//   {
//     id: 55,
//     questionNo: '৫৫',
//     question: 'question',
//     answer: 'answer',
//   },
//   {
//     id: 56,
//     questionNo: '৫৬',
//     question: 'question',
//     answer: 'answer',
//   },
//   {
//     id: 57,
//     questionNo: '৫৭',
//     question: 'question',
//     answer: 'answer',
//   },
//   {
//     id: 58,
//     questionNo: '৫৮',
//     question: 'question',
//     answer: 'answer',
//   },
//   {
//     id: 59,
//     questionNo: '৫৯',
//     question: 'question',
//     answer: 'answer',
//   },
//   {
//     id: 60,
//     questionNo: '৬০',
//     question: 'question',
//     answer: 'answer',
//   },
